// <auto-generated />
namespace TravelPlanner2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class NewFeedback : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewFeedback));
        
        string IMigrationMetadata.Id
        {
            get { return "202505271007459_NewFeedback"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
